# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Run Algorithm

on:
  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
  
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Set your region
  
      - name: Run
        run: |
          export AWS_REGION="ap-southeast-1"
          export HOST_API_SECRET=${{ secrets.HOST_API_SECRET }}
          export DB_CREDENTIALS_SECRET=${{ secrets.DB_CREDENTIALS_SECRET }}
          go run ./explorer.go
